# Site settings
title: Raphael Feng | A blog
description: "My personal blog"
url: "http://raphaelfeng.github.io"
author:
  name: "Raphael Feng"
  email: "hello@raphaelfeng.com"
  url: "http://www.raphaelfeng.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: false
reverse: false

highlighter: pygments
